# Generated by Django 3.1.5 on 2021-01-27 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Url')),
                ('menushow', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('menutitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в меню')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Статья')),
                ('menuposition', models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню')),
                ('lastmod', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('name', models.CharField(max_length=200, verbose_name='Контакты')),
                ('iframe', models.TextField(max_length=50000, verbose_name='Код Страницы из карт')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефоны')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Url')),
                ('menushow', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('menutitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в меню')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Статья')),
                ('menuposition', models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню')),
                ('lastmod', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано (показывать на сайте)')),
                ('show_on_index', models.BooleanField(default=False, verbose_name='Показывать на главной')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
            },
        ),
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Robots',
                'verbose_name_plural': 'Robots',
            },
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Url')),
                ('menushow', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('menutitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в меню')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Статья')),
                ('menuposition', models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню')),
                ('lastmod', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('is_service', models.BooleanField(default=False, verbose_name='Услуга?')),
                ('img_path', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение для yandex turbo')),
                ('canonical', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='canonical')),
            ],
            options={
                'verbose_name': 'Текстовая страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=100, verbose_name='Телефоны')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Текст заявки')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Url')),
                ('menushow', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('menutitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в меню')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Статья')),
                ('menuposition', models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню')),
                ('lastmod', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('name', models.CharField(max_length=200, verbose_name='Название города')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Фото товара')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
            },
        ),
    ]
