# Generated by Django 3.1.5 on 2021-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='img_front',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Основное Изображение'),
        ),
    ]
