# Generated by Django 3.1.5 on 2021-01-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210128_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_hit',
            field=models.BooleanField(default=False, verbose_name='Хит?'),
        ),
        migrations.AddField(
            model_name='item',
            name='label_new',
            field=models.BooleanField(default=False, verbose_name='Новика?'),
        ),
    ]
