# Generated by Django 3.1.5 on 2021-01-28 18:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210128_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='alt Изображения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('display_home', models.BooleanField(default=False, verbose_name='Отображать на главной?')),
            ],
            options={
                'verbose_name': 'Изображения для слайдеров',
                'verbose_name_plural': 'Изображения для слайдеров',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='img',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья'),
        ),
    ]
