# Generated by Django 3.1.5 on 2021-01-29 06:20

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210128_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Url')),
                ('menushow', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('menutitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в меню')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья')),
                ('menuposition', models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню')),
                ('lastmod', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Категории проектов',
                'verbose_name_plural': 'Категории проектов',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=200, verbose_name='Url')),
                ('menushow', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, null=True, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('menutitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в меню')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Статья')),
                ('menuposition', models.IntegerField(blank=True, null=True, verbose_name='Позиция в меню')),
                ('lastmod', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('img_front', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Основное Изображение')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.catproject', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
