# Generated by Django 3.1.5 on 2021-02-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='catproject',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='canonical'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='canonical'),
        ),
        migrations.AddField(
            model_name='img',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='canonical'),
        ),
        migrations.AddField(
            model_name='item',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='canonical'),
        ),
        migrations.AddField(
            model_name='project',
            name='canonical',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='canonical'),
        ),
        migrations.AddField(
            model_name='slider',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='Товар'),
        ),
    ]
