# Generated by Django 3.1.5 on 2021-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210201_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='catitems',
            name='ico',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка в меню'),
        ),
    ]
