# Generated by Django 3.1.5 on 2021-02-02 06:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210201_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcatitems',
            options={'verbose_name': 'Под категории для товаров', 'verbose_name_plural': 'Под категории для товаров'},
        ),
        migrations.AddField(
            model_name='item',
            name='des_right',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание в правой части товара'),
        ),
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Alt картинки'),
        ),
    ]
