# Generated by Django 3.1.5 on 2021-02-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210202_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upsell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='К какому товару')),
                ('ups', models.ManyToManyField(related_name='upsellitem', to='main.Item', verbose_name='Какие товары')),
            ],
            options={
                'verbose_name': 'Похожие товары',
                'verbose_name_plural': 'Похожие товары',
            },
        ),
        migrations.CreateModel(
            name='Crosssell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='К какому товару')),
                ('ups', models.ManyToManyField(related_name='crosselitem', to='main.Item', verbose_name='Какие товары')),
            ],
            options={
                'verbose_name': 'Сопутствующие товары',
                'verbose_name_plural': 'Сопутствующие товары',
            },
        ),
    ]
