# Generated by Django 3.1.5 on 2021-02-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_crosssell_upsell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosssell',
            old_name='ups',
            new_name='cross',
        ),
    ]
