# Generated by Django 3.1.5 on 2021-02-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210202_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_kv',
            field=models.FloatField(default=0, verbose_name='Цена кв.м'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена п.м.'),
        ),
    ]
