# Generated by Django 3.1.5 on 2021-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210202_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dlina',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='item',
            name='obrob',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Обработка'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена п.м.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_kv',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена кв.м'),
        ),
    ]
