# Generated by Django 3.1.5 on 2021-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210203_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catitems',
            options={'ordering': ['menuposition'], 'verbose_name': 'Категории для товаров', 'verbose_name_plural': 'Категории для товаров'},
        ),
        migrations.AlterModelOptions(
            name='catproject',
            options={'ordering': ['menuposition'], 'verbose_name': 'Категории проектов', 'verbose_name_plural': 'Категории проектов'},
        ),
        migrations.AlterModelOptions(
            name='podcatitems',
            options={'ordering': ['menuposition'], 'verbose_name': 'Под категории для товаров', 'verbose_name_plural': 'Под категории для товаров'},
        ),
        migrations.AlterField(
            model_name='item',
            name='dlina',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Длина (с указанием ед.измерения)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер мм'),
        ),
    ]
