# Generated by Django 3.1.5 on 2021-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['menuposition'], 'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='price_for_wt',
            field=models.BooleanField(default=False, verbose_name='Цена за штуку?'),
        ),
    ]
