# Generated by Django 3.1.5 on 2021-05-05 07:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210311_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akcii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание акции')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
