# Generated by Django 3.1.5 on 2021-05-05 08:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_akcii'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcii',
            name='textpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.textpage', verbose_name='страницы'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название в банере')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание в банере')),
                ('textpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.textpage', verbose_name='страницы')),
            ],
            options={
                'verbose_name': 'Изображения для слайдеров',
                'verbose_name_plural': 'Изображения для слайдеров',
            },
        ),
    ]
