# Generated by Django 3.1.5 on 2021-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='https://api.telegram.org/bot', max_length=200, null=True, verbose_name='URL')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='TOKEN')),
                ('chanel_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название канала или id')),
                ('who', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID назначения')),
            ],
            options={
                'verbose_name': 'Данные от телеграм бота',
                'verbose_name_plural': 'Данные от телеграм бота',
            },
        ),
    ]
