# Generated by Django 3.1.5 on 2021-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='who',
            field=models.CharField(blank=True, default='main', max_length=200, null=True, verbose_name='ID назначения'),
        ),
    ]
